# -*- coding: utf-8 -*-
"""ml_project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KBnVwEj7gbj40oBmhZaMZ_TkMAmDM6-C
"""

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import accuracy_score, classification_report

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC



df = pd.read_csv("train_u6lujuX_CVtuZ9i.csv")

print("Dataset Preview:\n", df.head())


if "Loan_ID" in df.columns:
    df.drop("Loan_ID", axis=1, inplace=True)

df["Loan_Status"] = df["Loan_Status"].map({'Y': 1, 'N': 0})


# Fill numerical NaNs with the mean before Label Encoding
for col in df.select_dtypes(include=np.number).columns:
    if df[col].isnull().any():
        df[col] = df[col].fillna(df[col].mean())

# Now apply forward fill for any remaining NaNs (e.g., in categorical columns before encoding if any remain)
df = df.ffill()


le = LabelEncoder()
for col in df.select_dtypes(include='object').columns:
    df[col] = le.fit_transform(df[col])

print("\nAfter Preprocessing:\n", df.head())



X = df.drop("Loan_Status", axis=1)
y = df["Loan_Status"]



X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)



scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)


lr = LogisticRegression(max_iter=1000)
lr.fit(X_train_scaled, y_train)
y_pred_lr = lr.predict(X_test_scaled)

dt = DecisionTreeClassifier(random_state=42)
dt.fit(X_train, y_train)
y_pred_dt = dt.predict(X_test)


rf = RandomForestClassifier(random_state=42)
rf.fit(X_train, y_train)
y_pred_rf = rf.predict(X_test)


svm = SVC()
svm.fit(X_train_scaled, y_train)
y_pred_svm = svm.predict(X_test_scaled)

print("\n=== Accuracy ===")
print("Logistic Regression:", accuracy_score(y_test, y_pred_lr))
print("Decision Tree:", accuracy_score(y_test, y_pred_dt))
print("Random Forest:", accuracy_score(y_test, y_pred_rf))
print("SVM:", accuracy_score(y_test, y_pred_svm))



if "Gender" in X_test.columns:
    test_df = X_test.copy()
    test_df["Actual"] = y_test.values
    test_df["Predicted"] = y_pred_rf

    group_0 = test_df[test_df["Gender"] == 0]["Predicted"]
    group_1 = test_df[test_df["Gender"] == 1]["Predicted"]

    print("\n=== Fairness Check (Gender) ===")
    print("Group 0 Approval Rate:", np.mean(group_0))
    print("Group 1 Approval Rate:", np.mean(group_1))
else:
    print("\nGender column not found for fairness check.")



if "Gender" in df.columns:
    print("\n=== Training WITHOUT Gender ===")

    X_ng = df.drop(["Loan_Status", "Gender"], axis=1)
    y_ng = df["Loan_Status"]

    X_train_ng, X_test_ng, y_train_ng, y_test_ng = train_test_split(
        X_ng, y_ng, test_size=0.2, random_state=42
    )

    rf_ng = RandomForestClassifier(random_state=42)
    rf_ng.fit(X_train_ng, y_train_ng)
    y_pred_ng = rf_ng.predict(X_test_ng)

    print("Random Forest Accuracy (No Gender):", accuracy_score(y_test_ng, y_pred_ng))


print("\n=== Classification Report (Random Forest) ===")
print(classification_report(y_test, y_pred_rf))
# Accuracy values from your models
accuracy = [
    accuracy_score(y_test, y_pred_lr),
    accuracy_score(y_test, y_pred_dt),
    accuracy_score(y_test, y_pred_rf),
    accuracy_score(y_test, y_pred_svm)
]
approval_rates = [
    np.mean(group_0),
    np.mean(group_1)
]
import matplotlib.pyplot as plt


plt.figure()
plt.bar(["LogReg", "DecisionTree", "RandomForest", "SVM"], accuracy)
plt.xlabel("Models")
plt.ylabel("Accuracy")
plt.title("Model Accuracy Comparison")
plt.show()

plt.figure()
plt.bar(["Group 0", "Group 1"], approval_rates)
plt.xlabel("Groups")
plt.ylabel("Approval Rate")
plt.title("Fairness Comparison (Gender)")
plt.show()